#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Vitafeu\EasyMVC\CommandUtils;

// Set the project root
Vitafeu\EasyMVC\Globals::setProjectRoot(__DIR__ . '/');

// Load .env file
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/');
$dotenv->load();

// Check if running from command line
if (!defined('STDIN')) {
    fwrite(STDERR, "This script must be run from the command line.");
    exit(1);
}

// Create an instance of the CommandUtils and call the handleCommand method
$commandUtils = new CommandUtils();
$commandUtils->handleCommand($argv);