site_name: Easy MVC
site_author: Benjamin Feurly

repo_url: https://github.com/vitafeu/easy-mvc
repo_name: vitafeu/easy-mvc

copyright: Copyright &copy; 2024 Benjamin Feurly

theme:
  language: en
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/vitafeu
      name: Support me on Ko-fi !
    - icon: fontawesome/solid/paper-plane
      link: mailto:professional@vitafeu.com
      name: Email me
    - icon: fontawesome/brands/github
      link: https://github.com/vitafeu
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/471369652212203540
      name: Discord


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Using the framework: 
    - Prologue: using-the-framework.md
    - Routing: routing.md
    - Controllers: controllers.md
    - Views: views.md
    - Models: models.md
  - References: references.md
